### ISSUE TITLE
Feature Request: Ability to set variable due dates

### ISSUE THREAD

**Issue by nsaripalli** [scottquach/Canvas-Assignments-Transfer-For-Todoist#14]
It would be nice to have the option to be able to set the due date of all assignments x days before it is actually due. 
I would imagine there could be two ways of having the actual due date incorporated either as a sub task or within the task name itself.

**Comment by scottquach** [comment]
Great idea! would you expect such config to apply to all assignments or to be configured as a prompt upon adding individual assignments?

**Comment by nsaripalli** [comment]
I could totally see both being valid approaches.
I personally have a cron job running this script on my server a few times a day, so I would prefer an option where no user interaction is required if a config for the date time shift is set somewhere.

**Comment by stacksjb** [comment]
For me, I would NOT want this because then the due date is not accurate - but I can see how it would be really cool if this was an option. The trouble is that current logic is based on due date and due dates are being updated based on what they are in canvas, so I don't think storing it somewhere else or making a subtask is a good option unless the logic is updated to track tasks based on something else.

One way this could be implemented would be to add some logic and config for a "date_skew" type parameter, and then modify all dates pulled from Canvas (before they're checked against Todoist or stored) by that amount. You could even just add this to the code and set the change to 0 by default.

That said, modifying dates in Python is a bit difficult if the dates aren't parsed in, which I don't think they currently are (we're just pulling, checking, and submitting values from one API to the other as far as I am aware).

Would love some further comments or thoughts on how this could be accomplished - it seems like a lot of work to me when you can instead just put a filter in Todoist for "Due in next 3 days" and work on keeping that done.

**Comment by stacksjb** [comment]
I'm going to close this for now, we can reopen if there is further interest. It would be a fair chunk of work to implement something like this and require tracking date/times in multiple places.

I'd recommend rejecting this as you can create a filter in Todoist for "Due in <x> days" which will show the tasks ahead of time based on what you configure, so you can work on that.
