### ISSUE TITLE
All on one list

### ISSUE THREAD

**Issue by ItsMacto** [scottquach/Canvas-Assignments-Transfer-For-Todoist#32]
Is it possible to add all to one list on Todo so free users can add all of there classes. Right now its limited to just 5

**Comment by stacksjb** [comment]
Unfortunately, not with the current logic. It would require some re-work.
You can temporarily pay for more and not lose projects if you downgrade. 
The 5-project limit is new by Todoist and was added more recently.

What exactly are you thinking - adding all of your assignments to a single project?

**Comment by ItsMacto** [comment]
Yeah my idea was to just add all to a big project named canvas. Another possibility with this but would be a good bit of work is then have the labels to dustings the different classes in the one project. Ether way appreciate the free project very helpful!

**Comment by stacksjb** [comment]
In the future I am going to be redoing the code so that it will be operating on a per-class and per-project basis, so I'm not sure how to easily address this since a project to course mapping is necessary.

Rejecting for now, but if I think of a better possible way to do this I might revisit it. 

I had thought of using sections, but I would like to implement modules to sections at some point down the road.
